### ISSUE TITLE
WordPress?

### ISSUE THREAD

**Issue by georgeolaru** [razwan/library#1]
@razwan Ar trebui sa trecem design-ul pe WordPress?

**Comment by georgeolaru** [comment]
@cristianfrumusanu te bagi sa treci pe WordPress? Zic sa folosim post type-ul default (Posts) pentru carti. 

Si doar arhiva, cum propunea si @razwan - eu zic ordonate dupa categorii (eg. Design, Creativity).

**Comment by cristianfrumusanu** [comment]
@georgeolaru ma bag sa trec pe WP.

**Comment by razwan** [comment]
E o idee buna. Altfel vezi ce se intampla da crek index.pho e de ajuns gen. Oricum cred ca o sa vreau sa fac ceva mai high-fidelity cand vin daca se va fi ajuns la o concluzie.

**Comment by georgeolaru** [comment]
@razwan Tu stai in concediu acum
